### ISSUE TITLE
Is there a way to suppress fluidsynth error messages?

### ISSUE THREAD

**Issue by SamusAranX** [Rainbow-Dreamer/sf2_loader#5]
For some reason, `get_all_instrument_names()` only gives me a fraction of the instruments contained in a soundfont, so I'm doing a cheap version of it myself:

```py
def get_sf2_instruments(path):
	sf2_file = sf2.sf2_loader(path)

	instruments = {}
	for b in range(128):
		instruments[b] = {}
		for i in range(128):
			inst_name = sf2_file.get_instrument_name(bank_num=b, preset_num=i)
			if not inst_name:
				continue

			instruments[b][i] = inst_name

			print(f"{b:>3} - {i:>3}: {inst_name}")

	return instruments
```

The problem is that for every non-existent bank/preset combination, I get a message like
> fluidsynth: error: There is no preset with bank number 1 and preset number 2 in SoundFont 1

printed to my console, which is less than desirable. Can I turn these off somewhere?

**Comment by Rainbow-Dreamer** [comment]
This is because the function `get_all_instrument_names` is actually designed to be given all the instrument names of current bank, I think your implementation of returning a dictionary of instruments of all banks is pretty good, I will add this functionality as a new function (maybe called `all_instruments`) in the next version, thanks.
For the fluidsynth errors, it is from the fluidsynth C/C++ compiled exe, which means it is hard coded into fluidsynth executable, and python does not have the ability to prevent print messages from C/C++ codes as far as I know, so I'm afraid I cannot turn off the warnings. You can try to comment out all of the printf warning messages in the C/C++ source codes provided by the fluidsynth official and recompile it to a new executable, the compile tutorial can be found [here](https://github.com/FluidSynth/fluidsynth/wiki/BuildingWithCMake). (Note: This is kind of a tedious work, and I have tried this a month ago to compile a no-warning version of fluidsynth on Windows but it is not successful :( But it is possible to suppress all of the warnings using this method)

**Comment by Rainbow-Dreamer** [comment]
Good news, I have found a solution to suppress warnings from C shared library by using py package, now the latest version of sf2_loader does not show warnings when you are getting the instrument names. Cheers :)
